### ISSUE TITLE
Refactor Node.java

### ISSUE THREAD

**Issue by rprtr258** [rprtr258/spbsu-homework#48]
I've selected [**Node.java**](https://github.com/rprtr258/spbsu-homework/blob/664c1e822ecda6eeac15302d2e6578296498855f/semester2/hw4/4.2/src/main/java/com/rprtr258/Node.java#L1-L208) for refactoring, which is a module of **170** lines of code and **26** incoming calls. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Separate Concerns in Modules** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Avoid large modules with high fan-in (nr. of incoming calls).
- **Why**❓ 
This keeps the codebase loosely coupled which makes it easier to minimize the consequences of changes.
- **How** 🔧 
Identify and extract responsibilities of large modules into smaller ones and hide implementation details behind interfaces. Target having modules that have no more than 10 incoming calls.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by jzuken** [comment]
это что? :)

**Comment by rprtr258** [comment]
There were no need in extracting Node.java in separate class🔧 Now it is in NodeWrapper as inner class 👍and everything is OK✨ 💯
